services:
  user-api:
    build: .
    image: user-system
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - database

  database:
    image: postgres:latest
    container_name: postgres_users
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5400:5432
    volumes:
      - pgdata:/var/lib/postgress/database

  redis:
    image: redis:7
    ports:
      - "6379:6379"
  
  prometheus:
    image: prom/prometheus
    ports: 
      - "9090:9090"
    volumes: 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  pgdata:
