version: "3.8"

services:
  user-api:
    build: .
    image: user-system
    ports:
      - "8080:3000"
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:7
    ports:
      - "6379:6379"
